version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6378:6379"

  server:
    build: ..
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - redis
    ports:
      - "7071:7071"
    environment:
      - REDIS_ADDR=redis:6379
      - CONFIG_PATH=/app/config.yaml
